trigger:
- master

pool:
  vmImage: ubuntu-latest

variables:
  project: './src/Wealho.Ui'
  buildPlatform: 'Any CPU'
  buildConfiguration: 'Release'
  tag: '$(Build.SourceVersion)'

steps:
- task: DotNetCoreCLI@2
  name: 'restore'
  inputs:
    command: 'restore'
    projects: $(project)
    feedsToUse: 'select'
  
- task: DotNetCoreCLI@2
  name: 'build' 
  inputs:
    command: 'build'
    projects: '$(project)/Wealho.Ui.csproj'
    arguments: '--no-restore'

- task: Docker@2
  name: 'publish_container'
  inputs:
    containerRegistry: 'docker hub'
    repository: 'dariuszek/wealho-ui'
    command: 'buildAndPush'
    Dockerfile: '$(project)/Dockerfile'
    tags: "latest"